title: Andriy Shyrokoryadov
description: Developer and data scientist's blog
author: Andriy Shyrokoryadov
logo: /static/img/avatar.jpg
github: https://github.com/ashyrokoriadov?tab=repositories
about: .Net Developer, data scientist

baseurl: ""
url: ""

allowsearch: false

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
